- name: ec2 launcher
  hosts: localhost
  connection: local
  tasks:
  - name: launching ec2
    ec2:
       key_name: Wordpress
       instance_type: t3.medium
       region: us-west-2
       user_data: "{{ lookup('file', 'wordpress.sh') }}"     
       image: ami-000340e2c761dddcd
       wait: yes
       group: default
       count: 1
       vpc_subnet_id: subnet-05f3ac8491de89718
       assign_public_ip: yes
